from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


FEATURE_FAMILIES: Dict[str, List[str]] = {
    "F1_TrendMomentum": [
        "LagRet_1",
        "LagRet_5",
        "LagRet_20",
        "Trend_30",
        "Trend_2h",
        "Trend_slope",
        "RSI14",
        "MACD_z",
    ],
    "F2_VolRisk": [
        "ATR20_log",
        "RealVol20_log",
        "VolRegime",
        "MktVolRank",
    ],
    "F3_Relative": [
        "MktRet_1",
        "MktRet_3",
        "MktRet_6",
        "StockMinusMkt_1",
        "StockMinusMkt_3",
        "SectorMinusMkt_3",
    ],
    "F4_SessionContext": [
        "VWAP_Dist",
        "SessionOpenDist_ATR",
        "OpeningRangeBreakout",
        "TimeSinceNewHigh",
        "TimeSinceNewLow",
        "IntradayVolPercentile",
        "RelativeVolumeTime",
        "MinuteNorm",
    ],
    "F5_CandleShape": [
        "BodyToRange",
        "UpperWickRatio",
        "LowerWickRatio",
        "CloseLocation_3",
        "RetSkew_5",
    ],
    "F6_PersistenceBreakout": [
        "Breakout_3bar",
        "SignPersistence_5",
        "RegimeBull",
        "RegimeBear",
    ],
    "F7_CrossSectionalRanks": [
        "XS_Rank_StockMinusMkt_1",
        "XS_Rank_StockMinusMkt_3",
        "XS_Rank_StockMinusMkt_6",
        "XS_Rank_SectorMinusMkt_3",
        "XS_Rank_RelativeVolumeTime",
        "XS_Rank_VolAdjStockMinusMkt_1",
        "XS_Rank_VolAdjStockMinusMkt_3",
        "XS_LeaderSpread_3",
    ],
    "F8_LeadershipPersistence": [
        "XS_LeaderTop20",
        "XS_LaggardBottom20",
        "XS_LeaderPersist_3",
        "XS_LaggardPersist_3",
        "XS_LeaderPersist_6",
        "XS_LaggardPersist_6",
        "XS_Rank_Change_3",
        "XS_VolumeLeaderSpread",
    ],
    "F9_MarketStateLabels": [
        "MarketStateBullCalm",
        "MarketStateBullStress",
        "MarketStateBearCalm",
        "MarketStateBearStress",
        "MarketStateTransition",
        "MarketStateTrendScore",
        "MarketStateVolPressure",
    ],
    "F10_MultiScaleContext": [
        "MultiScaleRet_3h",
        "MultiScaleRet_6h",
        "MultiScaleRet_12h",
        "MultiScaleTrendGap",
        "MultiScaleMomentumAlignment",
        "MultiScaleVolRatio_3v20",
        "MultiScaleRangeCompression_3v12",
        "MultiScaleBodyPressure_3",
        "MultiScaleBreakoutPressure_3",
    ],
    "F11_PortfolioRankContext": [
        "XS_Rank_StockMinusMkt_1",
        "XS_Rank_StockMinusMkt_3",
        "XS_Rank_StockMinusMkt_6",
        "XS_Rank_SectorMinusMkt_3",
        "XS_Rank_RelativeVolumeTime",
        "XS_Rank_VolAdjStockMinusMkt_1",
        "XS_Rank_VolAdjStockMinusMkt_3",
        "XS_LeaderSpread_3",
        "XS_VolumeLeaderSpread",
        "XS_LeaderPersist_3",
        "XS_LaggardPersist_3",
        "XS_LeaderPersist_6",
        "XS_LaggardPersist_6",
        "XS_Rank_Change_3",
    ],
    "F12_SecondTimeframeContext": [
        "STF15_IntrahourRet",
        "STF15_PathEfficiency",
        "STF15_FirstHalfRet",
        "STF15_SecondHalfRet",
        "STF15_FirstHalfShare",
        "STF15_VolBurst",
        "STF15_VolBurstRatio",
        "STF15_RangeToOpen",
        "STF15_FailedBreakoutScore",
        "STF15_CloseLocation",
        "STF15_RelVolumeMean",
        "STF15_WickPressure",
        "STF15_BodyPressure",
        "STF15_BreakoutPressure",
    ],
    "F13_IntrahourPathV1": [
        "STF15_PathEfficiency",
        "STF15_PositiveShare",
        "STF15_NegativeShare",
        "STF15_SignFlipRate",
        "STF15_FirstHalfRet",
        "STF15_SecondHalfRet",
        "STF15_LateStrengthShare",
        "STF15_MaxAdverseExcursion",
        "STF15_HighBeforeLow",
        "STF15_LowBeforeHigh",
        "STF15_RejectionScore",
        "STF15_FailedBreakoutScore",
    ],
    "F14_BreadthContext": [
        "BreadthAdvFrac_1",
        "BreadthRelAdvFrac_3",
        "BreadthLeaderFrac",
        "BreadthLaggardFrac",
        "BreadthTrendPressure",
        "BreadthLeaderSpread",
        "BreadthDispersion_3",
        "BreadthVolumePressure",
        "BreadthExpansion_3",
        "BreadthParticipation",
    ],
    "F15_TimeDistributionV2": [
        "STF15_FirstHalfRet",
        "STF15_SecondHalfRet",
        "STF15_FirstHalfShare",
        "STF15_LateStrengthShare",
        "STF15_TimeImbalance",
        "STF15_EarlyVol",
        "STF15_LateVol",
        "STF15_LateVolRatio",
        "STF15_LastQuarterRet",
        "STF15_LastQuarterShare",
        "STF15_EarlyExhaustionScore",
        "STF15_CloseQuarterDominance",
    ],
    "F16_Native15mPath": [
        "M15_Ret_4",
        "M15_PathEfficiency_4",
        "M15_PositiveShare_4",
        "M15_SignFlipRate_4",
        "M15_TimeImbalance_4",
        "M15_EarlyExhaustion_4",
        "M15_RejectionScore_4",
        "M15_CloseLocation_4",
        "M15_BreakoutPressure_4",
        "M15_BodyPressure_4",
        "M15_VolRatio_2v8",
    ],
    "F17_Native15mFailedBreakout": [
        "M15_RejectionScore_4",
        "M15_CloseLocation_4",
        "M15_BreakoutPressure_4",
        "M15_BodyPressure_4",
        "M15_SignFlipRate_4",
        "M15_TimeImbalance_4",
        "M15_EarlyExhaustion_4",
        "M15_VolRatio_2v8",
    ],
    "F18_Native15mOpenDrive": [
        "MinuteNorm",
        "SessionOpenDist_ATR",
        "OpeningRangeBreakout",
        "VWAP_Dist",
        "RelativeVolumeTime",
        "IntradayVolPercentile",
        "TimeSinceNewHigh",
        "TimeSinceNewLow",
        "BodyToRange",
        "UpperWickRatio",
        "LowerWickRatio",
        "Breakout_3bar",
        "SignPersistence_5",
    ],
    "F19_Native15mSessionPhase": [
        "MinuteNorm",
        "RelativeVolumeTime",
        "IntradayVolPercentile",
        "VWAP_Dist",
        "SessionOpenDist_ATR",
        "BodyToRange",
        "UpperWickRatio",
        "LowerWickRatio",
        "M15_TimeImbalance_4",
        "M15_EarlyExhaustion_4",
        "M15_RejectionScore_4",
        "M15_CloseLocation_4",
        "Breakout_3bar",
        "SignPersistence_5",
    ],
    "F20_Native15mHoldingHorizon": [
        "M15_Ret_4",
        "M15_PathEfficiency_4",
        "M15_PositiveShare_4",
        "M15_SignFlipRate_4",
        "M15_TimeImbalance_4",
        "M15_EarlyExhaustion_4",
        "M15_RejectionScore_4",
        "M15_CloseLocation_4",
        "M15_BreakoutPressure_4",
        "M15_BodyPressure_4",
        "M15_VolRatio_2v8",
        "MinuteNorm",
        "RelativeVolumeTime",
        "IntradayVolPercentile",
        "VWAP_Dist",
        "SessionOpenDist_ATR",
    ],
    "F21_Native15mTopKEventRank": [
        "XS_Rank_StockMinusMkt_1",
        "XS_Rank_StockMinusMkt_3",
        "XS_Rank_StockMinusMkt_6",
        "XS_Rank_SectorMinusMkt_3",
        "XS_Rank_RelativeVolumeTime",
        "XS_Rank_VolAdjStockMinusMkt_1",
        "XS_Rank_VolAdjStockMinusMkt_3",
        "XS_LeaderSpread_3",
        "XS_VolumeLeaderSpread",
        "XS_LeaderPersist_3",
        "XS_LaggardPersist_3",
        "XS_LeaderPersist_6",
        "XS_LaggardPersist_6",
        "XS_Rank_Change_3",
        "RelativeVolumeTime",
        "IntradayVolPercentile",
        "VWAP_Dist",
        "SessionOpenDist_ATR",
        "MinuteNorm",
        "BodyToRange",
        "CloseLocation_3",
        "Breakout_3bar",
    ],
}


@dataclass(frozen=True)
class ExperimentDef:
    experiment_id: str
    target_id: str
    horizon: int
    label_type: str
    feature_families: List[str]
    model_class: str
    regime_filter: Optional[str] = None
    selection_rule: Optional[str] = None
    notes: str = ""


DEFAULT_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E101",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Primary opportunity detector: h=2, F4+F5",
    ),
    ExperimentDef(
        experiment_id="E105",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Opportunity detector with persistence/breakout context",
    ),
    ExperimentDef(
        experiment_id="E102",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Legacy h=3 opportunity baseline",
    ),
]


FOCUSED_EXECUTION_EXPERIMENTS: List[ExperimentDef] = list(DEFAULT_EXPERIMENTS)


E004_SWEEP_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E101",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=2, F4+F5",
    ),
    ExperimentDef(
        experiment_id="E102",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=3, F4+F5",
    ),
    ExperimentDef(
        experiment_id="E103",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=4, F4+F5",
    ),
    ExperimentDef(
        experiment_id="E104",
        target_id="T3",
        horizon=5,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=5, F4+F5",
    ),
    ExperimentDef(
        experiment_id="E105",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=2, F4+F5+F6",
    ),
    ExperimentDef(
        experiment_id="E106",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=3, F4+F5+F6",
    ),
    ExperimentDef(
        experiment_id="E107",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=4, F4+F5+F6",
    ),
    ExperimentDef(
        experiment_id="E108",
        target_id="T3",
        horizon=5,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E004 neighborhood sweep: h=5, F4+F5+F6",
    ),
]


E102_REGIME_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E201",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="E102 volatility split: high-vol opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E202",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="E102 volatility split: low-vol opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E203",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="E102+F6 volatility split: high-vol opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E204",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="E102+F6 volatility split: low-vol opportunity detector",
    ),
]


E102_DEEPDIVE_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E201",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: high-volatility opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E202",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: low-volatility opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E203",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: high-volatility opportunity detector with persistence context",
    ),
    ExperimentDef(
        experiment_id="E204",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: low-volatility opportunity detector with persistence context",
    ),
    ExperimentDef(
        experiment_id="E205",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 0.20",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: opening-session opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E206",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MinuteNorm > 0.20 and MinuteNorm <= 0.70",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: mid-session opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E207",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 0.20",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: opening-session detector with persistence context",
    ),
    ExperimentDef(
        experiment_id="E208",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MinuteNorm > 0.20 and MinuteNorm <= 0.70",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: mid-session detector with persistence context",
    ),
    ExperimentDef(
        experiment_id="E209",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="RegimeBull == 1",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: bull-regime opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E210",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="RegimeBear == 1",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: bear-regime opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E211",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="RegimeBull == 1",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: bull-regime detector with persistence context",
    ),
    ExperimentDef(
        experiment_id="E212",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="RegimeBear == 1",
        selection_rule="prob>=0.60",
        notes="E102 deep-dive: bear-regime detector with persistence context",
    ),
]


GENERALIZATION_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E301",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Cross-stock opportunity baseline using relative and volatility context only",
    ),
    ExperimentDef(
        experiment_id="E302",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Cross-stock opportunity baseline with session structure added",
    ),
    ExperimentDef(
        experiment_id="E303",
        target_id="T3",
        horizon=6,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Longer-horizon generalization test using relative and volatility features",
    ),
    ExperimentDef(
        experiment_id="E304",
        target_id="T3",
        horizon=6,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Longer-horizon generalization test with session context",
    ),
    ExperimentDef(
        experiment_id="E305",
        target_id="T2",
        horizon=6,
        label_type="regression",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="elasticnet",
        notes="Cross-stock alpha regression using relative and volatility context",
    ),
    ExperimentDef(
        experiment_id="E306",
        target_id="T2",
        horizon=12,
        label_type="regression",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="elasticnet",
        notes="Longer-horizon alpha regression generalization test with session context",
    ),
]


E302_SWEEP_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E321",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=2 with relative and volatility context",
    ),
    ExperimentDef(
        experiment_id="E322",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=3 with relative and volatility context",
    ),
    ExperimentDef(
        experiment_id="E323",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=4 with relative and volatility context",
    ),
    ExperimentDef(
        experiment_id="E324",
        target_id="T3",
        horizon=5,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=5 with relative and volatility context",
    ),
    ExperimentDef(
        experiment_id="E325",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=2 with session context",
    ),
    ExperimentDef(
        experiment_id="E302",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 anchor: h=3 with session context",
    ),
    ExperimentDef(
        experiment_id="E327",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=4 with session context",
    ),
    ExperimentDef(
        experiment_id="E328",
        target_id="T3",
        horizon=5,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=5 with session context",
    ),
    ExperimentDef(
        experiment_id="E329",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=2 with session and persistence context",
    ),
    ExperimentDef(
        experiment_id="E330",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=3 with session and persistence context",
    ),
    ExperimentDef(
        experiment_id="E331",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=4 with session and persistence context",
    ),
    ExperimentDef(
        experiment_id="E332",
        target_id="T3",
        horizon=5,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="E302 sweep: h=5 with session and persistence context",
    ),
]


GENERALIZATION_NEXT_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E401",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="T4 setup-quality branch: h=3 using session, candle shape, and persistence context",
    ),
    ExperimentDef(
        experiment_id="E402",
        target_id="T4",
        horizon=6,
        label_type="binary",
        feature_families=["F1_TrendMomentum", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="T4 continuation-quality branch: h=6 using trend, relative, session, and persistence context",
    ),
    ExperimentDef(
        experiment_id="E403",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="High-volatility opportunity branch: h=2 with relative, volatility, and session context",
    ),
    ExperimentDef(
        experiment_id="E404",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        regime_filter="MktVolRank >= 0.70",
        selection_rule="prob>=0.60",
        notes="High-volatility opportunity branch: h=3 with relative, volatility, and session context",
    ),
    ExperimentDef(
        experiment_id="E405",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="Low-volatility opportunity branch: h=2 with relative, volatility, and session context",
    ),
    ExperimentDef(
        experiment_id="E406",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="logistic",
        regime_filter="MktVolRank <= 0.30",
        selection_rule="prob>=0.60",
        notes="Low-volatility opportunity branch: h=3 with relative, volatility, and session context",
    ),
    ExperimentDef(
        experiment_id="E407",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Setup-proxy branch: h=2 using session structure and breakout persistence only",
    ),
    ExperimentDef(
        experiment_id="E408",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Setup-proxy branch: h=3 using session, candle shape, and breakout persistence",
    ),
]


GENERALIZATION_WAVE2_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E411",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape"],
        model_class="lgbm_reg",
        regime_filter="MinuteNorm <= 0.20",
        notes="Session-isolated alpha: opening segment using relative, session, and candle features",
    ),
    ExperimentDef(
        experiment_id="E412",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape"],
        model_class="lgbm_reg",
        regime_filter="MinuteNorm > 0.20 and MinuteNorm <= 0.70",
        notes="Session-isolated alpha: mid-session segment using relative, session, and candle features",
    ),
    ExperimentDef(
        experiment_id="E413",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F1_TrendMomentum", "F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="lgbm_reg",
        regime_filter="OpeningRangeBreakout != 0",
        notes="Setup library: trend continuation after opening-range breakout",
    ),
    ExperimentDef(
        experiment_id="E414",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F1_TrendMomentum", "F3_Relative", "F4_SessionContext"],
        model_class="lgbm_reg",
        regime_filter="Trend_2h * VWAP_Dist < 0",
        notes="Setup library: pullback-to-trend using trend, relative, and session context",
    ),
    ExperimentDef(
        experiment_id="E415",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="lgbm_clf",
        regime_filter="Breakout_3bar != 0 and (CloseLocation_3 <= 0.20 or CloseLocation_3 >= 0.80)",
        selection_rule="prob>=0.60",
        notes="Setup library: failed breakout reversal quality test",
    ),
    ExperimentDef(
        experiment_id="E416",
        target_id="T2",
        horizon=6,
        label_type="regression",
        feature_families=["F2_VolRisk", "F3_Relative"],
        model_class="lgbm_reg",
        regime_filter="MktVolRank >= 0.30 and MktVolRank <= 0.70",
        notes="Setup library: relative-strength carry in mid-volatility tape",
    ),
]


CROSS_SECTIONAL_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E501",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks"],
        model_class="logistic",
        regime_filter="XS_Rank_StockMinusMkt_3 >= 0.60",
        selection_rule="prob>=0.60",
        notes="Cross-sectional continuation: relative leaders vs market/sector context",
    ),
    ExperimentDef(
        experiment_id="E502",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="logistic",
        regime_filter="XS_Rank_StockMinusMkt_3 >= 0.60",
        selection_rule="prob>=0.60",
        notes="Cross-sectional continuation with leadership persistence",
    ),
    ExperimentDef(
        experiment_id="E503",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F7_CrossSectionalRanks", "F4_SessionContext"],
        model_class="logistic",
        regime_filter="(XS_Rank_StockMinusMkt_1 >= 0.80) or (XS_Rank_StockMinusMkt_1 <= 0.20)",
        selection_rule="prob>=0.60",
        notes="Cross-sectional mean reversion from short-horizon relative extremes",
    ),
    ExperimentDef(
        experiment_id="E504",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="logistic",
        regime_filter="(XS_Rank_StockMinusMkt_1 >= 0.80) or (XS_Rank_StockMinusMkt_1 <= 0.20)",
        selection_rule="prob>=0.60",
        notes="Cross-sectional mean reversion with persistence and session context",
    ),
    ExperimentDef(
        experiment_id="E505",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="logistic",
        regime_filter="(XS_LeaderPersist_3 >= 2) or (XS_LaggardPersist_3 >= 2)",
        selection_rule="prob>=0.60",
        notes="Leadership persistence branch for repeated leaders/laggards",
    ),
    ExperimentDef(
        experiment_id="E506",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F2_VolRisk", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="logistic",
        regime_filter="(XS_LeaderPersist_6 >= 3) or (XS_LaggardPersist_6 >= 3)",
        selection_rule="prob>=0.60",
        notes="Leadership persistence branch with volatility conditioning",
    ),
    ExperimentDef(
        experiment_id="E507",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks"],
        model_class="logistic",
        regime_filter="(XS_Rank_SectorMinusMkt_3 >= 0.70) or (XS_Rank_SectorMinusMkt_3 <= 0.30)",
        selection_rule="prob>=0.60",
        notes="Sector-relative spread behavior among cross-sectional extremes",
    ),
    ExperimentDef(
        experiment_id="E508",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="logistic",
        regime_filter="((XS_Rank_SectorMinusMkt_3 >= 0.70) or (XS_Rank_SectorMinusMkt_3 <= 0.30)) and (MktVolRank >= 0.25) and (MktVolRank <= 0.75)",
        selection_rule="prob>=0.60",
        notes="Sector-relative spread behavior in calmer market tape",
    ),
]


ABLATION_GRID_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E601",
        target_id="T1",
        horizon=3,
        label_type="regression",
        feature_families=["F1_TrendMomentum"],
        model_class="lgbm_reg",
        notes="Ablation grid: T1 with pure trend/momentum family",
    ),
    ExperimentDef(
        experiment_id="E602",
        target_id="T1",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative"],
        model_class="lgbm_reg",
        notes="Ablation grid: T1 with pure market-relative family",
    ),
    ExperimentDef(
        experiment_id="E603",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative"],
        model_class="lgbm_reg",
        notes="Ablation grid: T2 with relative alpha family",
    ),
    ExperimentDef(
        experiment_id="E604",
        target_id="T2",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F4_SessionContext"],
        model_class="lgbm_reg",
        notes="Ablation grid: T2 with relative plus session structure",
    ),
    ExperimentDef(
        experiment_id="E605",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T3 with session structure only",
    ),
    ExperimentDef(
        experiment_id="E606",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T3 with relative plus session structure",
    ),
    ExperimentDef(
        experiment_id="E607",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T3 with relative, session, and candle shape",
    ),
    ExperimentDef(
        experiment_id="E608",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T3 with relative plus cross-sectional rank context",
    ),
    ExperimentDef(
        experiment_id="E609",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T3 with relative plus cross-sectional persistence",
    ),
    ExperimentDef(
        experiment_id="E610",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T4 with setup-quality family",
    ),
    ExperimentDef(
        experiment_id="E611",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T4 with relative plus cross-sectional ranks",
    ),
    ExperimentDef(
        experiment_id="E612",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F7_CrossSectionalRanks", "F8_LeadershipPersistence"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Ablation grid: T4 with relative plus cross-sectional persistence",
    ),
]


SETUP_REGIME_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E701",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="(RegimeBull >= 0.5) and (MktVolRank <= 0.70)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S1: bull-regime continuation in calmer tape",
    ),
    ExperimentDef(
        experiment_id="E702",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout"],
        model_class="lgbm_clf",
        regime_filter="(RegimeBull >= 0.5) and (MktVolRank <= 0.70)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S1: bull-regime continuation with relative confirmation",
    ),
    ExperimentDef(
        experiment_id="E703",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="((VWAP_Dist <= -0.50) or (SessionOpenDist_ATR <= -0.50)) and (RegimeBull >= 0.5)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S2: pullback-to-trend after stretch below VWAP/open",
    ),
    ExperimentDef(
        experiment_id="E704",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape"],
        model_class="lgbm_clf",
        regime_filter="((VWAP_Dist >= 0.75) or (SessionOpenDist_ATR >= 0.75)) and (ADX_weak >= 0.5)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S3: mean reversion from stretched weak-trend tape",
    ),
    ExperimentDef(
        experiment_id="E705",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F2_VolRisk", "F3_Relative", "F4_SessionContext"],
        model_class="lgbm_clf",
        regime_filter="(MktVolRank >= 0.20) and (MktVolRank <= 0.65) and (StockMinusMkt_3 >= 0)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S4: relative-strength carry in calmer tape",
    ),
    ExperimentDef(
        experiment_id="E706",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout"],
        model_class="lgbm_clf",
        regime_filter="(OpeningRangeBreakout != 0) and (BodyToRange <= -0.25 or BodyToRange >= 0.25)",
        selection_rule="prob>=0.60",
        notes="Setup-regime S5: failed-breakout reversal quality",
    ),
]


MARKET_STATE_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E801",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F9_MarketStateLabels"],
        model_class="logistic",
        regime_filter="MarketStateBullCalm >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: calm bull opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E802",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F9_MarketStateLabels"],
        model_class="lgbm_clf",
        regime_filter="MarketStateBullCalm >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: calm bull setup quality",
    ),
    ExperimentDef(
        experiment_id="E803",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F9_MarketStateLabels"],
        model_class="lgbm_clf",
        regime_filter="MarketStateTransition >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: transition regime opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E804",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout", "F9_MarketStateLabels"],
        model_class="lgbm_clf",
        regime_filter="MarketStateTransition >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: transition regime setup quality",
    ),
    ExperimentDef(
        experiment_id="E805",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F9_MarketStateLabels"],
        model_class="lgbm_clf",
        regime_filter="MarketStateBearStress >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: stressed bear relative opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E806",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape", "F9_MarketStateLabels"],
        model_class="lgbm_clf",
        regime_filter="MarketStateBearStress >= 0.5",
        selection_rule="prob>=0.60",
        notes="Market-state branch: stressed bear setup quality",
    ),
]


MULTISCALE_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E901",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F10_MultiScaleContext"],
        model_class="logistic",
        regime_filter="MultiScaleMomentumAlignment >= 0.10",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: aligned opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E902",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F10_MultiScaleContext"],
        model_class="lgbm_clf",
        regime_filter="MultiScaleMomentumAlignment >= 0.10",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: aligned setup quality",
    ),
    ExperimentDef(
        experiment_id="E903",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F10_MultiScaleContext"],
        model_class="lgbm_clf",
        regime_filter="MultiScaleRangeCompression_3v12 <= 0.95",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: compressed-range opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E904",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape", "F10_MultiScaleContext"],
        model_class="lgbm_clf",
        regime_filter="MultiScaleRangeCompression_3v12 <= 0.95",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: compressed-range setup quality",
    ),
    ExperimentDef(
        experiment_id="E905",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F6_PersistenceBreakout", "F10_MultiScaleContext"],
        model_class="lgbm_clf",
        regime_filter="MultiScaleVolRatio_3v20 >= 1.05",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: expanding-volatility opportunity detector",
    ),
    ExperimentDef(
        experiment_id="E906",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape", "F6_PersistenceBreakout", "F10_MultiScaleContext"],
        model_class="lgbm_clf",
        regime_filter="MultiScaleVolRatio_3v20 >= 1.05",
        selection_rule="prob>=0.60",
        notes="Multi-scale branch: expanding-volatility setup quality",
    ),
]


PORTFOLIO_RANK_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1001",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F11_PortfolioRankContext"],
        model_class="elasticnet",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: relative-strength continuation",
    ),
    ExperimentDef(
        experiment_id="E1002",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F5_CandleShape", "F11_PortfolioRankContext"],
        model_class="lgbm_reg",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: relative-strength mean reversion",
    ),
    ExperimentDef(
        experiment_id="E1003",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F4_SessionContext", "F11_PortfolioRankContext"],
        model_class="lgbm_reg",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: sector-relative session ranking",
    ),
    ExperimentDef(
        experiment_id="E1004",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F2_VolRisk", "F3_Relative", "F11_PortfolioRankContext"],
        model_class="lgbm_reg",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: market-relative volatility-normalized ranking",
    ),
    ExperimentDef(
        experiment_id="E1005",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F2_VolRisk", "F8_LeadershipPersistence", "F11_PortfolioRankContext"],
        model_class="lgbm_reg",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: leadership persistence",
    ),
    ExperimentDef(
        experiment_id="E1006",
        target_id="T6",
        horizon=3,
        label_type="regression",
        feature_families=["F3_Relative", "F9_MarketStateLabels", "F11_PortfolioRankContext"],
        model_class="lgbm_reg",
        selection_rule="top3_bottom3_session_open",
        notes="Portfolio ranking: regime-aware relative ranking",
    ),
]


SECOND_TIMEFRAME_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1101",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F12_SecondTimeframeContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="60m setup quality with 15m path-quality context",
    ),
    ExperimentDef(
        experiment_id="E1102",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F6_PersistenceBreakout", "F12_SecondTimeframeContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="60m breakout setup with 15m failed-breakout confirmation",
    ),
    ExperimentDef(
        experiment_id="E1103",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F9_MarketStateLabels", "F12_SecondTimeframeContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="60m setup quality with market-state and 15m volatility context",
    ),
    ExperimentDef(
        experiment_id="E1104",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F4_SessionContext", "F5_CandleShape", "F12_SecondTimeframeContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="60m relative setup with 15m exhaustion context",
    ),
    ExperimentDef(
        experiment_id="E1105",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F1_TrendMomentum", "F3_Relative", "F12_SecondTimeframeContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="60m trend and relative strength with 15m continuation quality",
    ),
    ExperimentDef(
        experiment_id="E1106",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F10_MultiScaleContext", "F12_SecondTimeframeContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="60m opportunity score with 15m entry-efficiency context",
    ),
]


INTRAHOUR_PATH_V1_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1201",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F13_IntrahourPathV1"],
        model_class="logistic",
        notes="Intrahour continuation quality using path efficiency and consistency features",
    ),
    ExperimentDef(
        experiment_id="E1202",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F6_PersistenceBreakout", "F13_IntrahourPathV1"],
        model_class="logistic",
        notes="Intrahour continuation with breakout persistence and path-quality confirmation",
    ),
    ExperimentDef(
        experiment_id="E1203",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F5_CandleShape", "F13_IntrahourPathV1"],
        model_class="lgbm_clf",
        notes="Intrahour failed-breakout and rejection structure for setup-quality targeting",
    ),
    ExperimentDef(
        experiment_id="E1204",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F9_MarketStateLabels", "F13_IntrahourPathV1"],
        model_class="lgbm_clf",
        notes="State-aware intrahour path thesis with regime context and adversity ordering",
    ),
]


BREADTH_CONTEXT_60M_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1301",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F14_BreadthContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Breadth participation and thrust context for continuation-quality setups",
    ),
    ExperimentDef(
        experiment_id="E1302",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F14_BreadthContext"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Relative-strength setups conditioned on market breadth exhaustion and expansion",
    ),
    ExperimentDef(
        experiment_id="E1303",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F5_CandleShape", "F14_BreadthContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Setup-quality classifier with breadth dispersion and participation context",
    ),
    ExperimentDef(
        experiment_id="E1304",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F14_BreadthContext"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Market-state-aware setup-quality signal using breadth internals as confirmation",
    ),
]


TIME_DISTRIBUTION_V2_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1401",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F4_SessionContext", "F15_TimeDistributionV2"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Session-context setup detector using early-vs-late move timing inside the hour",
    ),
    ExperimentDef(
        experiment_id="E1402",
        target_id="T3",
        horizon=3,
        label_type="binary",
        feature_families=["F5_CandleShape", "F15_TimeDistributionV2"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Candle and timing-distribution signal emphasizing late-hour confirmation vs early exhaustion",
    ),
    ExperimentDef(
        experiment_id="E1403",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F15_TimeDistributionV2"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Setup-quality signal using market-state plus time-of-information distribution inside the hour",
    ),
    ExperimentDef(
        experiment_id="E1404",
        target_id="T4",
        horizon=3,
        label_type="binary",
        feature_families=["F3_Relative", "F15_TimeDistributionV2"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Relative-strength timing-distribution signal using late confirmation and close-quarter dominance",
    ),
]


NATIVE_15M_EXECUTION_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1501",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F4_SessionContext", "F16_Native15mPath"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m continuation-quality signal using direct path and timing structure over the last hour",
    ),
    ExperimentDef(
        experiment_id="E1502",
        target_id="T3",
        horizon=4,
        label_type="binary",
        feature_families=["F5_CandleShape", "F16_Native15mPath"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m signal using candle quality plus path stability for next-hour opportunity",
    ),
    ExperimentDef(
        experiment_id="E1503",
        target_id="T4",
        horizon=8,
        label_type="binary",
        feature_families=["F3_Relative", "F16_Native15mPath"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m relative-strength timing signal with direct path decomposition over a 2-hour barrier horizon",
    ),
    ExperimentDef(
        experiment_id="E1504",
        target_id="T4",
        horizon=8,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F16_Native15mPath"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m state-aware path signal for 2-hour continuation vs failure",
    ),
]


NATIVE_15M_FAILED_BREAKOUT_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1601",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F5_CandleShape", "F17_Native15mFailedBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m failed upside-breakout and rejection detector using candle structure plus rejection/event features",
    ),
    ExperimentDef(
        experiment_id="E1602",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F4_SessionContext", "F17_Native15mFailedBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m failed-breakout event detector with session-phase context for open-drive and late-session rejection behavior",
    ),
    ExperimentDef(
        experiment_id="E1603",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F3_Relative", "F17_Native15mFailedBreakout"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m failed-breakout event signal with relative-strength context for short-horizon continuation vs reversal outcome",
    ),
    ExperimentDef(
        experiment_id="E1604",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F17_Native15mFailedBreakout"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m state-aware failed-breakout event signal for stress-vs-calm rejection behavior",
    ),
]


NATIVE_15M_OPEN_DRIVE_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1701",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F18_Native15mOpenDrive", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 1.70",
        selection_rule="prob>=0.60",
        notes="Native 15m opening-drive event detector using opening-range context and candle conviction in the early session",
    ),
    ExperimentDef(
        experiment_id="E1702",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F18_Native15mOpenDrive", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 1.85",
        selection_rule="prob>=0.60",
        notes="Native 15m open-drive persistence signal focused on early breakout continuation with session-aware context",
    ),
    ExperimentDef(
        experiment_id="E1703",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F3_Relative", "F18_Native15mOpenDrive"],
        model_class="lgbm_clf",
        regime_filter="MinuteNorm <= 2.00",
        selection_rule="prob>=0.60",
        notes="Native 15m relative open-drive signal for names outperforming the tape during the opening phase",
    ),
    ExperimentDef(
        experiment_id="E1704",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F18_Native15mOpenDrive"],
        model_class="lgbm_clf",
        regime_filter="MinuteNorm <= 2.00",
        selection_rule="prob>=0.60",
        notes="Native 15m state-aware open-drive signal for calm-vs-stress opening behavior and follow-through quality",
    ),
]


NATIVE_15M_SESSION_PHASE_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1801",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F19_Native15mSessionPhase", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 1.75",
        selection_rule="prob>=0.60",
        notes="Native 15m early-session drive-quality detector using session-phase pressure, wick/body quality, and recent local path behavior",
    ),
    ExperimentDef(
        experiment_id="E1802",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F19_Native15mSessionPhase", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MinuteNorm > 1.75 and MinuteNorm <= 2.25",
        selection_rule="prob>=0.60",
        notes="Native 15m mid-session continuation-vs-fade signal using session-phase persistence and intrabar quality",
    ),
    ExperimentDef(
        experiment_id="E1803",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F3_Relative", "F19_Native15mSessionPhase"],
        model_class="lgbm_clf",
        regime_filter="MinuteNorm > 1.75 and MinuteNorm <= 2.50",
        selection_rule="prob>=0.60",
        notes="Native 15m relative session-pressure signal for names carrying better than the tape through the middle session",
    ),
    ExperimentDef(
        experiment_id="E1804",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F19_Native15mSessionPhase"],
        model_class="lgbm_clf",
        regime_filter="MinuteNorm > 2.25",
        selection_rule="prob>=0.60",
        notes="Native 15m late-session repricing signal using market-state context plus session-phase exhaustion and rejection structure",
    ),
]


NATIVE_15M_HOLDING_HORIZON_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E1901",
        target_id="T3",
        horizon=1,
        label_type="binary",
        feature_families=["F20_Native15mHoldingHorizon", "F5_CandleShape"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m short-hold event detector for one-bar follow-through using local path and candle-quality context",
    ),
    ExperimentDef(
        experiment_id="E1902",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F20_Native15mHoldingHorizon", "F6_PersistenceBreakout"],
        model_class="logistic",
        selection_rule="prob>=0.60",
        notes="Native 15m medium-short hold event detector to test whether two-bar persistence is the monetizable holding horizon",
    ),
    ExperimentDef(
        experiment_id="E1903",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F3_Relative", "F20_Native15mHoldingHorizon"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m medium hold relative-strength horizon test for events that need more room than the shortest bars",
    ),
    ExperimentDef(
        experiment_id="E1904",
        target_id="T4",
        horizon=8,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F20_Native15mHoldingHorizon"],
        model_class="lgbm_clf",
        selection_rule="prob>=0.60",
        notes="Native 15m long-intraday hold horizon test for events that only monetize with longer follow-through inside the same session",
    ),
]


NATIVE_15M_TOPK_EVENT_RANK_EXPERIMENTS: List[ExperimentDef] = [
    ExperimentDef(
        experiment_id="E2001",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F21_Native15mTopKEventRank", "F5_CandleShape"],
        model_class="logistic",
        regime_filter="MinuteNorm <= 1.90 and XS_Rank_StockMinusMkt_3 >= 0.75 and RelativeVolumeTime >= 1.10 and IntradayVolPercentile >= 0.55",
        selection_rule="prob>=0.60",
        notes="Native 15m early leader-selection thesis that only ranks within strong relative-volume event slices instead of scoring the whole universe continuously",
    ),
    ExperimentDef(
        experiment_id="E2002",
        target_id="T3",
        horizon=2,
        label_type="binary",
        feature_families=["F21_Native15mTopKEventRank", "F6_PersistenceBreakout"],
        model_class="logistic",
        regime_filter="MinuteNorm > 1.55 and MinuteNorm <= 2.30 and XS_Rank_RelativeVolumeTime >= 0.70 and XS_LeaderPersist_3 >= 0.50 and IntradayVolPercentile >= 0.45",
        selection_rule="prob>=0.60",
        notes="Native 15m mid-session leader continuation thesis that ranks only among names with persistent cross-sectional leadership and live participation",
    ),
    ExperimentDef(
        experiment_id="E2003",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F3_Relative", "F21_Native15mTopKEventRank"],
        model_class="lgbm_clf",
        regime_filter="XS_Rank_SectorMinusMkt_3 >= 0.70 and XS_Rank_StockMinusMkt_3 >= 0.70 and MktVolRank >= 0.20 and MktVolRank <= 0.80",
        selection_rule="prob>=0.60",
        notes="Native 15m sector-leader carry thesis that only ranks inside relatively favorable breadth and volatility conditions",
    ),
    ExperimentDef(
        experiment_id="E2004",
        target_id="T4",
        horizon=4,
        label_type="binary",
        feature_families=["F9_MarketStateLabels", "F21_Native15mTopKEventRank"],
        model_class="lgbm_clf",
        regime_filter="XS_Rank_VolAdjStockMinusMkt_3 >= 0.70 and RegimeBull >= 0.5 and MarketStateBullCalm >= 0.5",
        selection_rule="prob>=0.60",
        notes="Native 15m calm-leader event thesis that ranks only inside relatively favorable bull-calm slices rather than across all bars",
    ),
]
